plugins {
    id 'java'
}

group 'io.divetrip'
version '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
	implementation project(':dive-trip-library');

	// web
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// batch
	implementation 'org.springframework.boot:spring-boot-starter-batch'
	testImplementation 'org.springframework.batch:spring-batch-test'

	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}

tasks.named('test') {
	useJUnitPlatform()
}

test.onlyIf {
	!project.hasProperty('test')
}

springBoot {
	mainClass.set("io.divetrip.batch.DiveTripBatchApplication")
}
