plugins {
    id 'java'
}

group 'io.divetrip'
version '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
	implementation project(':dive-trip-library')

	implementation 'org.springframework.boot:spring-boot-starter-batch'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.batch:spring-batch-test'
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}

//tasks.named('test') {
//	useJUnitPlatform()
//}

springBoot {
	mainClass.set("io.divetrip.batch.DiveTripBatchApplication")
}
